# Generated by Django 5.2.14 on 2026-05-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('common_name', models.CharField(max_length=255)),
                ('botanical_name', models.CharField(max_length=255)),
                ('medicinal_benefits', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
